import "./page.css"

import type {Metadata} from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Credits & Acknowledgments",
    description: "Thanks to those who made this possible",
};

export default function Credits() {
    return (
        <div id="credits">
            <h1>Special thanks</h1>
            <p>To my wonderful incredible players.</p>
            <p>
                Without you guys I would not have anyone to DM for and I would never
                have had this incredible opportunity. You are all amazing and your love for the game and world makes me
                happy beyond words ❤️
            </p>
            <hr/>
            <h1>Disclaimer</h1>
            <p>
                AI was used to generate many of the images used on this site. Unless otherwise specified, all images you
                see here were generated by <Link href="https://chatgpt.com/" target="_blank"
                                                 rel="noopener noreferrer">ChatGPT</Link> or provided via the players.
            </p>
            <p className="footnote">
                I do not support AI taking jobs from artists, I am simply not rich enough to commission art for
                every NPC, nor am I talented enough to draw my own :(
            </p>
            <p className="footnote">
                Where possible I encourage people to buy real art from real artists!
            </p>
            <h2>Additional resources</h2>
            <p>
                The following resources were not AI generated and are used under fair use.
            </p>
            <ul>
                <li>
                    Skull from <Link href="https://www.vecteezy.com" target="_blank"
                                     rel="noopener noreferrer">Vecteezy</Link>
                </li>
                <li>
                    Naomi Freewind from <Link
                    href="https://www.deviantart.com/hybrid-dragoness/art/Kamas-the-Aarakocra-Ranger-842990708"
                    target="_blank"
                    rel="noopener noreferrer">Hybrid Arts</Link> (found via Google Images)
                </li>
                <li>
                    Various images from <Link href="https://www.dndbeyond.com/" target="_blank"
                                              rel="noopener noreferrer">D&D Beyond</Link>
                </li>
            </ul>
            <hr/>
            <h1>Other tools</h1>
            <p>
                Quite a few technical tools were leveraged while making this project.
            </p>
            <ul>
                <li>
                    <Link href="https://www.npmjs.com/package/use-debounce" target="_blank"
                          rel="noopener noreferrer">Use Debounce</Link> for providing valuable debounce
                    functionality
                </li>
                <li>
                    <Link href="https://imagemagick.org/index.php" target="_blank"
                          rel="noopener noreferrer">ImageMagick</Link> for functionality that allowed scripted
                    manipulation and resizing of images
                </li>
                <li>
                    <Link href="https://react.dev/" target="_blank" rel="noopener noreferrer">React</Link> which was
                    used to make this webapp
                </li>
                <li>
                    <Link href="https://nextjs.org/" target="_blank" rel="noopener noreferrer">NextJS</Link> for
                    providing a solid foundation to build off of
                </li>
            </ul>
        </div>
    )
}