export const resizedImageUrl = function (defaultUrl: string, width: number, height: number): string {
    // For now, we are just very simple and change the URL so that the last `/` is replaced with the width and height
    // numbers matching the format generated by a script.
    // Maybe later on we can do file existence checks and closest matches, but this will do for now :)
    const pathParts = defaultUrl.split('/');
    if (pathParts.length == 0) {
        return defaultUrl;
    }

    pathParts.splice(-1, 0, `${width}x${height}`)
    return pathParts.join("/");
}
